### ISSUE TITLE
Missing PendingIntent mutability flag for app target Android 12 (targetSdkVersion 31)

### ISSUE THREAD

**Issue by cwdev19** [speedchecker/speedchecker-sdk-android#8]
Below is the error stack:

Caused by: java.lang.IllegalArgumentException: com.easy.vpn.free.super.fast: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.speedchecker.android.sdk.Workers.AlarmReceiver.d(AlarmReceiver.java:171)
        at com.speedchecker.android.sdk.Workers.AlarmReceiver.a(AlarmReceiver.java:112)
        at com.speedchecker.android.sdk.Workers.AlarmReceiver.b(AlarmReceiver.java:116)
        at com.speedchecker.android.sdk.BaseProbe.a(BaseProbe.java:81)
        at com.speedchecker.android.sdk.SpeedcheckerSDK.init(SpeedcheckerSDK.java:52)

**Comment by cwdev19** [comment]
Besides adding the flags for Android version S, seems like there's also a dependency with WorkManager, so adding the latest work-runtime dependency is needed:
https://stackoverflow.com/questions/68228666/targeting-s-version-10000-and-above-requires-that-one-of-flag-immutable-or-fl

**Comment by DenysYakubets** [comment]
Hello @cwdev19, unfortunately, our SDK doesn't support Android 12 yet. There are a lot of things that we need to improve and test (not only flag changes and WorkManager upgrading). 

We already have this task but it will be done only in Q1 2022. Unfortunately, we have a lot of tasks for this quarter.

Regards, Denys.

**Comment by anselmoshim** [comment]
I am also running into this issue when setting `targetSdkVersion 31`. It does seem to work for now on my Android 12 device if I leave setting to `targetSdkVersion 30`.

**Comment by DenysYakubets** [comment]
I think this issue was fixed in the new SDK version. Please, check:
`implementation 'com.speedchecker:android-sdk:4.2.142-demo'`

**Comment by huytvq** [comment]
Hi @DenysYakubets , I'm using version 4.2.142-demo and it doesn't work on android 12. Please help me!

**Comment by DenysYakubets** [comment]
Hi @huytvq, we released the new version "4.2.151-demo", please try and let me know. Thanks!

**Comment by jabouzi** [comment]
Hello even if it's closed did you find a solution to the issue? thanks.

**Comment by sterien7** [comment]
@DenysYakubets what is the solution for this one. Here the app still crashes on Android 12
